# Generated by Django 3.2.18 on 2023-03-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='row_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
